dg_jira_auth_homepage:
    pattern:  /hello_jira/{name}
    defaults: { _controller: DGJiraAuthBundle:Default:index }

dg_jira_auth_homepage:
    pattern:  /public/{alias}
    defaults: { _controller: DGJiraAuthBundle:Default:showPublicPage }

dg_jira_auth_homepage:
    pattern:  /private/{alias}
    defaults: { _controller: DGJiraAuthBundle:Default:showPrivatePage }
