parameters:
    dg_jira_auth.user_provider.class: DG\JiraAuthBundle\User\JiraUserProvider
    dg_jira_auth.listener.class: DG\JiraAuthBundle\Security\Firewall\JiraListener
    dg_jira_auth.provider.class: DG\JiraAuthBundle\Security\Authentication\Provider\JiraProvider
    dg_jira_auth.handler.class: DG\JiraAuthBundle\Security\Authentication\Handler\JiraAuthenticationHandler

services:
    dg_jira_auth.user_provider:
        class: %dg_jira_auth.user_provider.class%
        arguments:
            - @session

    dg_jira_auth.logout_handler:
        class: %dg_jira_auth.handler.class%

    dg_jira_auth.authentication_success_handler:
        class: %dg_jira_auth.handler.class%

    dg_jira_auth.authentication_failure_handler:
        class: %dg_jira_auth.handler.class%

    dg_jira_auth.authentication_provider:
        class: %dg_jira_auth.provider.class%
        arguments: [@dg_jira_auth.user_provider, '']

    dg_jira_auth.authentication_listener:
        class: %dg_jira_auth.listener.class%
        arguments:
            - @security.context
            - @security.authentication.manager
            - @security.authentication.session_strategy
            - @security.http_utils
            - ''
            - @dg_jira_auth.authentication_success_handler
            - @dg_jira_auth.authentication_failure_handler
            - ''
            - @logger
            - @event_dispatcher

