parameters:
    dg_jira_auth.listener.class: DG\JiraAuthBundle\Security\Firewall\JiraListener

services:
#    dg_jira_auth.example:
#        class: %dg_jira_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
